name: "IRC Notifications"
on:
  create:
  issues:
    types: [opened, reopened, closed, assigned, unassigned]

jobs:
  irc:
    runs-on: ubuntu-latest
    steps:
      - name: irc tag
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        with:
          channel: "#MPTCPUpstream"
          nickname: gh-tag-bot
          message: |
            New tag available: ${{ github.event.ref }} (by ${{ github.actor }})
      - name: irc issue open-close
        uses: rectalogic/notify-irc@v1
        if: >
          github.event_name == 'issues' &&
          (github.event.action == 'opened' ||
           github.event.action == 'reopened' ||
           github.event.action == 'closed')
        with:
          channel: "#MPTCPUpstream"
          nickname: gh-issues-bot
          message: |
            Issue #${{ github.event.issue.number }} has been ${{ github.event.action }} by ${{ github.actor }}.
            Issue title: "${{ github.event.issue.title }}"
            Issue opened by: ${{ github.event.issue.user.login }}
            URL: ${{ github.event.issue.html_url }}
      - name: irc issue assign
        uses: rectalogic/notify-irc@v1
        if: >
          github.event_name == 'issues' &&
          (github.event.action == 'assigned' ||
           github.event.action == 'unassigned')
        with:
          channel: "#MPTCPUpstream"
          nickname: gh-issues-bot
          message: |
            Issue #${{ github.event.issue.number }} has been ${{ github.event.action }} by ${{ github.actor }}.
            Assignee: ${{ github.event.assignee.login }}
            Issue title: ${{ github.event.issue.title }}
            Issue opened by: ${{ github.event.issue.user.login }}
            URL: ${{ github.event.issue.html_url }}
